# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\FieldEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(784, 597)
        self.scrollArea = QtWidgets.QScrollArea(Frame)
        self.scrollArea.setGeometry(QtCore.QRect(110, 80, 521, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.fieldList = QtWidgets.QWidget()
        self.fieldList.setGeometry(QtCore.QRect(0, 0, 519, 409))
        self.fieldList.setObjectName("fieldList")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fieldList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.fieldList)
        self.editorName = QtWidgets.QLabel(Frame)
        self.editorName.setGeometry(QtCore.QRect(40, 20, 691, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.editorName.setFont(font)
        self.editorName.setAlignment(QtCore.Qt.AlignCenter)
        self.editorName.setObjectName("editorName")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(60, 520, 651, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.editorName.setText(_translate("Frame", "Editor Name"))
        self.saveButton.setText(_translate("Frame", "SAVE"))
        self.deleteButton.setText(_translate("Frame", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
