# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\ImageField.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(460, 300)
        Frame.setMinimumSize(QtCore.QSize(460, 300))
        Frame.setMaximumSize(QtCore.QSize(460, 300))
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ImageField = QtWidgets.QGroupBox(Frame)
        self.ImageField.setObjectName("ImageField")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ImageField)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 451, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 40, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.src = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.src.setMinimumSize(QtCore.QSize(0, 80))
        self.src.setMaximumSize(QtCore.QSize(16777215, 80))
        self.src.setObjectName("src")
        self.gridLayout.addWidget(self.src, 1, 1, 1, 1)
        self.alt = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.alt.setMinimumSize(QtCore.QSize(0, 80))
        self.alt.setMaximumSize(QtCore.QSize(16777215, 80))
        self.alt.setObjectName("alt")
        self.gridLayout.addWidget(self.alt, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uploadBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadBtn.sizePolicy().hasHeightForWidth())
        self.uploadBtn.setSizePolicy(sizePolicy)
        self.uploadBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.uploadBtn.setObjectName("uploadBtn")
        self.horizontalLayout.addWidget(self.uploadBtn)
        self.downloadBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadBtn.sizePolicy().hasHeightForWidth())
        self.downloadBtn.setSizePolicy(sizePolicy)
        self.downloadBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.downloadBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.downloadBtn.setObjectName("downloadBtn")
        self.horizontalLayout.addWidget(self.downloadBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.ImageField, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.ImageField.setTitle(_translate("Frame", "ImageField"))
        self.label_3.setText(_translate("Frame", "alt"))
        self.label.setText(_translate("Frame", "attachment"))
        self.label_2.setText(_translate("Frame", "src"))
        self.uploadBtn.setText(_translate("Frame", "UPLOAD"))
        self.downloadBtn.setText(_translate("Frame", "DOWNLOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
