# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\RuleField.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(613, 53)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(613, 35))
        Form.setMaximumSize(QtCore.QSize(613, 53))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete.sizePolicy().hasHeightForWidth())
        self.delete.setSizePolicy(sizePolicy)
        self.delete.setMinimumSize(QtCore.QSize(0, 35))
        self.delete.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete.setFont(font)
        self.delete.setObjectName("delete")
        self.horizontalLayout.addWidget(self.delete)
        self.comboL = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboL.sizePolicy().hasHeightForWidth())
        self.comboL.setSizePolicy(sizePolicy)
        self.comboL.setMinimumSize(QtCore.QSize(0, 35))
        self.comboL.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboL.setObjectName("comboL")
        self.horizontalLayout.addWidget(self.comboL)
        self.comboM = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboM.sizePolicy().hasHeightForWidth())
        self.comboM.setSizePolicy(sizePolicy)
        self.comboM.setMinimumSize(QtCore.QSize(0, 35))
        self.comboM.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboM.setObjectName("comboM")
        self.horizontalLayout.addWidget(self.comboM)
        self.data = QtWidgets.QTextEdit(Form)
        self.data.setMinimumSize(QtCore.QSize(0, 35))
        self.data.setMaximumSize(QtCore.QSize(150, 35))
        self.data.setObjectName("data")
        self.horizontalLayout.addWidget(self.data)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.delete.setText(_translate("Form", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
